### ISSUE TITLE
How to specify requested items

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyTrade#8]
The `[POST] /api/trades` endpoint only allows a filter object for wanted items. Where do I specify the item (tag), of the requested item(s).

**Comment by Ekwav** [comment]
There is no special restriction on tags and or a way to filter for just tags. The `ItemNameContains` filter could be used in that case

**Comment by Ekwav** [comment]
Also added a new `ItemTag` filter to specify the item Tag in case you want only exact matches.
