### ISSUE TITLE
Create Trade throws HTTP 500

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyTrade#9]
sky--5dc8c468c5-lmfht.d9779e6f7df41d694347b4c85c79a299

Request data:

`
[{"playerUuid":"cbf30125749d4134bba377e4f2d3a377","item":{"count":1,"description":"§7Damage: §c+100\n§7Strength: §c+100\n §8[§7✎§8]\n\n§9§d§lUltimate Wise V\n§7Reduces the ability mana cost of\n§7this item by §a50%§7.\n\n§6Ability: Instant Transmission  §e§lRIGHT CLICK\n§7Teleport §a8 blocks§7 ahead of\n§7you and gain §a+50 §f✦ Speed§7\n§7for §a3 seconds§7.\n§8Mana Cost: §325\n\n§7§8This item can be reforged!\n§8§l* §8Co-op Soulbound §8§l*\n§9§lRARE SWORD","enchantments":{"ultimate_wise":"5"},"extraAttributes":{"uid":"a56cee5a7830","uuid":"18669781-03b2-4a1c-8583-a56cee5a7830","donated_museum":1,"timestamp":"9/12/21 5:00 PM","tier":3},"icon":"https://sky.coflnet.com/static/icon/ASPECT_OF_THE_END","id":null,"itemName":"§9Aspect of the End","tag":"ASPECT_OF_THE_END"},"wantedItems":[{"filters":{"ItemTag":"ASPECT_OF_THE_END"}},{"filters":{"ItemTag":"ASPECT_OF_THE_VOID","Rarity":"LEGENDARY"}}]}]
`

**Comment by Ekwav** [comment]
relates to #7
